version: '3.8'

services:
  db:
    image: postgres:16
    container_name: pgdb
    ports:
      - "5433:5432"  # expose to host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gator
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

